language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: iQUFkisEnglXpY5mXjAbVuhRtvJlC2lRrTGGZ8o6cILQuWIxqc/91DHzOg0o/llTSj3ZUr7PRMG1WeOhABLRC6335KHsWRM6wEP2GMDSueMTY9AKEdQB6Ovx1UvakilZM95nkIymFyGgtmLPlk8mXU0DetDaHnq5j10RQ1gQ8lHO+zcBVjk7W1v3YJhJVotkcqA8uxzXTDOhAapsqIAnLEZtUJLQDe/HKh04Gr88G9CYH3xXPyCs+bxwebNboBor/a+7hdNS/mxk1aRFCU/NcC44Tt5duzcUY2CR8j5OA0R7ibeZ9eB6TWmRVk5HwhypT1krKE4nNBA9nCd0VlGJRujRPwbuDa9nGIITXDF7PR0PPJx9bmVjkMAi51XuHkjRB4GRa+vM+jYtuscdjnJTINjwuj016+u5MlcS1M0yCUCh/nQMzsJCRakE67J7jmLiw1GypTWkT0g0dELazYGmqbAxdOrLzgvN5L+cHj7abCGB0McLa0Lkujsjte0MNYrHWpwcLpIYz1YlFgsv0MC8S95vROKMeGmFIsHRJFDLO3xl8EIW1oqnpQW+nziFpL9YM/ND8XNmwC5h3mKjS1UvHb/FEnJoQABiy35aQtniTRRYt0DR8lQa3aLbu01bLFo53s+NACjp0j83hG9b7mkzsnpxAGNoqmVpf3MxIYOlDgA=
  app: mental-health-fe
  on:
    repo: mental-health-org/mental-health-fe
    branch: main
env: 
