language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: BmJlcVlrMCiiX4r7gQBHmaUFwtuVuvzQpNCK/WnY8USLX+9BiqBmW7Jjv2wUeMn/yz+pcNxzmh1nDCENFhjPeOkH6JKpK0LjgPHvZ/fl/Vmh0VuRgwb6D6X3COfONPilVDwYs62HVWl4HycBc7hzitJ8+T3aAzXAPb1xQyYEGnj1J2nPDvJrtv30gudQU8jmlhhyuAykT+N2XPx7ifxzMxkOH0SJB3mPbnraT/FsxwN3V3ZhR7O37gBEejZqk+W3dSA9fPAB1O+lqDVTh8ZBspOyHaFW/6ErSv146XspdDnTz5Y5fRsBOq+ERD6Wrt7tu/kMFKh1XPUet5IsvUlKeKpg3oTzSjUobLMiVoE2aizC3XA1iPYMiiodeckEqUNtUYy/iamgnofxwleyLz7fyTstFcijZtWCI9JcU0ZPmk8fDbsIQfAboPn3+jRp/erpYXJ0fvghKUp/ar92CBE2zJwXQkTPPmkDsl0PXJziuXgojhC16TLUILapB6yQYxnkSO+KaefAogwjGsWGJ7D2810fEsmID6NbZKfgb6G+F0J+8DFVNNRjmHrv7hntDh799WifCQMTYYSdjmvEIO8g09Hr74glrC7LwEqAT4d2RHLBmbJuQ/HFLB3oEcRGqhsU2FlXxbgtDtrqAwKIw4LqlSbB3RNX1OEQ5olMA63Dyj4=
  app: mental-health-fe
  on:
    repo: mental-health-org/mental-health-fe
    branch: main
env: 
