language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: TdVqVJnWeIY15j3sptIgSXGKUoy9l2eZrVMXY6OnNcD2e8MHceR/U+Vegd/UXP4trkpldw2y3dtvxsyvA8+GEtLjPIpcyM2jyzfqhMJr2qdGuG0G7//BWXld8cAH5Uk2cLEtHtp0nHJEbVAuw0eVEzms6pHeiu7ozeXkwLH9bAQUBLUPNe7QsQRD06CgJzgJSWovwUzRkKLPO6rGz3aACU56EEZyTCCAghSZp7ad3VtMLLE6ZOzijhGwIEFkqAwo+Hzjod3jTcCn+wIrhFiFVT5TatBqC2eLoSsNVlzsAr8K9uiRNd2yyli5UsvU0Fh1qw2WZAx+An9tpA5YYUV1zyeIfRRNDVJretqWg9uWxhuQouS63zq8OcUCuXQVqYW5ExjQNTsgIIGV2tcluiVkx92wzHWg5KfGMDp9z1DSb7hq8P0kvZ7vG2HYYw3EBCBefx9XGvntWoEM7OWn1rhLPDcnVocGhjp6jmqEJWcNHRKtQ2XYaW92+DbR0q3emyDVL7XHtmkozbrEOG3cHvsbYR/KoJGTpTbpf7zcBvWvPn0w/WgZVu8vTATSSDHYnwj15/jlmXxBWtqfobtpmUt9pva0jwrpMaq9RUwmmyFdXYByb2ZJd5UiAOvTd5lLf7BU7lBw83QebWa+SB6VD5L3Yu+IfkIWVTtj/3GiaFfdjSY=
  app: mental-health-fe
  on:
    repo: mental-health-org/mental-health-fe
    branch: main
env: 
addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

script:
  - npm start &
  - npm run cy:run
  - kill $(jobs -p) || true